# -*- coding: utf-8 -*-
"""DAUP_Unit-4_Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jbEf-ZVvcVKRxdkxk4uHIZWTo4DFSwCo
"""

#4.1) Pandas DataSeries:
#i)Write a Pandas program to create and display a one-dimensional array-like object
#containing an array of data using Pandas module.

import pandas as pd

# Create a Pandas Series
data = pd.Series([1, "2", 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])

# Display the Pandas Series
print(data)

#ii) Convert Pandas Series to Python List and its Type

import pandas as pd

# Create a Pandas Series
data = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])

# Convert Pandas Series to Python List
list_data = data.tolist()

# Print the list
print("List:", list_data)

# Print the type of list
print("Type of list:", type(list_data))

# Convert Pandas Series index and values to Python List
list_index = data.index.tolist()
list_values = data.values.tolist()

# Print the lists
print("List of Index:", list_index)
print("List of Values:", list_values)

#4.2) Pandas DataFrames:
#Consider Sample Python dictionary data and list labels:
#exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily','Michael',
#'Matthew', 'Laura', 'Kevin', 'Jonas'],
#'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
#'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
#'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
#labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
#i)Write a Pandas program to create and display a DataFrame from a specified dictionary
#data which has the index labels.

import pandas as pd
import numpy as np

# Define the dictionary data
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily','Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
# Define the index labels
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create a DataFrame
df = pd.DataFrame(exam_data, index=labels)

# Display the DataFrame
print(df)

"""df = pd.DataFrame(exam_data, index=labels)

df = pd.DataFrame(exam_data)
"""

#ii) Change the name 'James' to 'Suresh'

# Change the name 'James' to 'Suresh'
df["Name"] = df["name"].replace("James", "Suresh")

# Display the updated DataFrame
print(df)

#iii) Insert a new column

df['age'] = [20, 21, 19, 22, 20, 21, 19, 22, 20, 21]

# Display the updated DataFrame
print(df)

#iv) Get list from DataFrame column headers

columns = df.columns.tolist()

# Display the list of column headers
print(columns)

#v) Get the data type of each column

dtypes = df.dtypes

# Display the data types
print(dtypes)