# -*- coding: utf-8 -*-
"""DAUP UNIT-3 LAB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_4xG0kXF6xvNQgllrg15fkT6zIpnhJWG
"""

import numpy as np

#3.1 (a) To get help on the add() function
import numpy as np
help(np.add)

#3.1 (a) To get help on the add() function
import numpy as np
print(np.info(np.add))

#(b) To test whether none of the elements of a given array is zero.
import numpy as np
arr = np.array([1, 2, 3, 4])
print("\nAll elements are non-zero:", np.all(arr))

#(c) To create an element-wise comparison (greater, greater_equal,
#less and less_equal,equal, equal within a tolerance) of two given arrays.
#greater
a = np.array([10, 20, 30])
b = np.array([15, 20, 25])

print("Greater:", np.greater(a, b))            # [False False  True]
print("Greater Equal:", np.greater_equal(a, b))# [False  True  True]
print("Less:", np.less(a, b))                  # [ True False False]
print("Less Equal:", np.less_equal(a, b))      # [ True  True False]
print("Equal:", np.equal(a, b))                # [False  True False]

# Check if arrays are almost equal (within tolerance)
c = np.array([1.00001, 2.00001])
d = np.array([1.00002, 2.00002])
print("Allclose:", np.allclose(c, d))          # True (within default tolerance)

#zeros
import numpy as np
print("\nZeros:", np.zeros((3,2)))

#ones
import numpy as np
print("Ones:", np.ones((2,3)))

#linspace
import numpy as np
print("Linspace:", np.linspace(100, 1500, 8))

#tolist
import numpy as np
print("Convert array to list:", a.tolist())

#3.2 NumPy Program Using Methods
#🔹 a. Extract numbers from array which are less and greater than a specified number
import numpy as np
arr = np.array([5, 15, 25, 35, 45])

# Extract numbers greater than 20
print("Greater than 20:", arr[arr > 20])  # [25 35 45]
print(arr)
# Extract numbers less than 30
print("Less than 30:", arr[arr < 30])     # [5 15 25]
print(arr)

#Find indices of max and min numbers along a given axis
arr2d = np.array([[10, 20, 30], [5, 25, 15]])

# Index of max along axis 0 (column-wise)
print("Argmax (axis=0):", np.argmax(arr2d, axis=0))  # [0 1 0]

# Index of min along axis 1 (row-wise)
print("Argmin (axis=1):", np.argmin(arr2d, axis=1))  # [0 0]

#Repr,Bincount and Unique
import numpy as np
a = np.array([1, 2, 1, 3, 2, 1, 4])
print("Repr:", repr(a))
print("Bincount:", np.bincount(a))
print("Unique values:", np.unique(a))